### ISSUE TITLE
setMask() cause webgl error

### ISSUE THREAD

**Issue by x-wk** [phaserjs/phaser#6251]
## Version

* Phaser Version:
Phaser v3.60.0-beta.12 (WebGL | Web Audio)
* Operating system:
win10
* Browser:
Microsoft Edge 106.0.1370.34

## Description
?.setMask(...) cause too many webgl errors.
```ts
[.WebGL-0000315C0AED9500] GL_INVALID_OPERATION: Feedback loop formed between Framebuffer and active Texture.
```

## Example Test Code

```ts
var config = {
    type: Phaser.WEBGL,
    width: 800,
    height: 600,
    backgroundColor: '#000000',
    parent: 'phaser-example',
    scene: {
        preload: preload,
        create: create,
        update: update
    }
};

var t = 0;
var image0, image1;
var game = new Phaser.Game(config);

function preload() {
    this.load.image('p0', 'assets/particles/red.png');
    this.load.image('p1', 'assets/particles/yellow.png');
    this.load.image('bunny', 'assets/sprites/bunny.png');
    this.load.image('mask1', 'assets/sprites/mask1.png');
}
function create() {

    const
        maskImage = this.make.image({ x: 300, y: 300, key: 'mask1', add: false }),
        groundMask = maskImage.createBitmapMask()

    image0 = this.add.tileSprite(300, 300, 300, 300, 'bunny')
        .setScrollFactor(1, 1)
        .setMask(groundMask)
}

function update() {
    image0.tilePositionY -= 2;
}
```

**Comment by x-wk** [comment]
The v3.60.0-beta.10 version worked fine

**Comment by photonstorm** [comment]
This is already fixed in the master branch (i.e. Beta 13). I would strongly recommend pulling down from master and doing a local build if you're going to be testing it lots, as this is moving a lot faster than the Beta releases can keep up with really.

**Comment by x-wk** [comment]
Thanks, I will.
Are there any books or articles that describe the knowledge of pipelines in detail? I have read the Examples, but I still don't know the differences and usage scenarios between these pipelines, and I want to customize the pipelines.
