### ISSUE TITLE
Pixel sprites from createFromAseprite are distorted in 3.60.0

### ISSUE THREAD

**Issue by likwidgames** [phaserjs/phaser#6327]
## Version

* Phaser Version: 3.60.0-beta.17

* Operating system: macOS

* Browser: Chrome

## Description

Pixel-based sprites are distorted in 3.60.0. This could be isolated to only sprites generated from "createFromAseprite". This issue does not exist in 3.55.x. Please see codepen below to example and steps to replicate.

## Example Test Code

https://codesandbox.io/s/distorted-sprites-mpdted?file=/src/index.ts

**Comment by likwidgames** [comment]
Image used for the Aseprite animation
![player](https://user-images.githubusercontent.com/31718144/208972219-21f56f11-c55e-4517-b351-24816e4a211e.png)

**Comment by likwidgames** [comment]
Aseprite json file for the animation below. (Will not let me upload a .json file).


```
{
  "frames": {
    "0": {
      "frame": {
        "x": 1,
        "y": 1,
        "w": 21,
        "h": 26
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 3,
        "y": 3,
        "w": 19,
        "h": 24
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "1": {
      "frame": {
        "x": 23,
        "y": 1,
        "w": 21,
        "h": 26
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 3,
        "y": 3,
        "w": 19,
        "h": 24
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "2": {
      "frame": {
        "x": 45,
        "y": 1,
        "w": 21,
        "h": 25
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 3,
        "y": 4,
        "w": 19,
        "h": 23
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "3": {
      "frame": {
        "x": 67,
        "y": 1,
        "w": 21,
        "h": 25
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 3,
        "y": 4,
        "w": 19,
        "h": 23
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "4": {
      "frame": {
        "x": 89,
        "y": 1,
        "w": 21,
        "h": 25
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 3,
        "y": 4,
        "w": 19,
        "h": 23
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "5": {
      "frame": {
        "x": 111,
        "y": 1,
        "w": 21,
        "h": 25
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 3,
        "y": 4,
        "w": 19,
        "h": 23
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "6": {
      "frame": {
        "x": 1,
        "y": 28,
        "w": 20,
        "h": 26
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 3,
        "y": 3,
        "w": 18,
        "h": 24
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "7": {
      "frame": {
        "x": 22,
        "y": 28,
        "w": 20,
        "h": 25
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 3,
        "y": 4,
        "w": 18,
        "h": 23
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "8": {
      "frame": {
        "x": 43,
        "y": 28,
        "w": 20,
        "h": 25
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 3,
        "y": 5,
        "w": 18,
        "h": 23
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "9": {
      "frame": {
        "x": 64,
        "y": 28,
        "w": 20,
        "h": 26
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 3,
        "y": 3,
        "w": 18,
        "h": 24
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "10": {
      "frame": {
        "x": 85,
        "y": 28,
        "w": 20,
        "h": 25
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 3,
        "y": 4,
        "w": 18,
        "h": 23
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "11": {
      "frame": {
        "x": 106,
        "y": 28,
        "w": 19,
        "h": 25
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 3,
        "y": 5,
        "w": 17,
        "h": 23
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "12": {
      "frame": {
        "x": 1,
        "y": 55,
        "w": 20,
        "h": 26
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 3,
        "y": 3,
        "w": 18,
        "h": 24
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "13": {
      "frame": {
        "x": 22,
        "y": 55,
        "w": 20,
        "h": 25
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 3,
        "y": 4,
        "w": 18,
        "h": 23
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "14": {
      "frame": {
        "x": 43,
        "y": 55,
        "w": 20,
        "h": 25
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 3,
        "y": 5,
        "w": 18,
        "h": 23
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "15": {
      "frame": {
        "x": 64,
        "y": 55,
        "w": 20,
        "h": 26
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 3,
        "y": 3,
        "w": 18,
        "h": 24
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "16": {
      "frame": {
        "x": 85,
        "y": 55,
        "w": 20,
        "h": 25
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 3,
        "y": 4,
        "w": 18,
        "h": 23
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "17": {
      "frame": {
        "x": 106,
        "y": 55,
        "w": 20,
        "h": 25
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 3,
        "y": 5,
        "w": 18,
        "h": 23
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "18": {
      "frame": {
        "x": 1,
        "y": 82,
        "w": 19,
        "h": 25
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 3,
        "y": 3,
        "w": 17,
        "h": 23
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "19": {
      "frame": {
        "x": 21,
        "y": 82,
        "w": 19,
        "h": 25
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 3,
        "y": 3,
        "w": 17,
        "h": 23
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "20": {
      "frame": {
        "x": 41,
        "y": 82,
        "w": 21,
        "h": 26
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 3,
        "y": 3,
        "w": 19,
        "h": 24
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "21": {
      "frame": {
        "x": 63,
        "y": 82,
        "w": 21,
        "h": 26
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 3,
        "y": 3,
        "w": 19,
        "h": 24
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "22": {
      "frame": {
        "x": 85,
        "y": 82,
        "w": 21,
        "h": 25
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 3,
        "y": 4,
        "w": 19,
        "h": 23
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "23": {
      "frame": {
        "x": 107,
        "y": 82,
        "w": 21,
        "h": 25
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 3,
        "y": 4,
        "w": 19,
        "h": 23
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "24": {
      "frame": {
        "x": 1,
        "y": 109,
        "w": 21,
        "h": 25
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 3,
        "y": 4,
        "w": 19,
        "h": 23
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "25": {
      "frame": {
        "x": 23,
        "y": 109,
        "w": 21,
        "h": 25
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 3,
        "y": 4,
        "w": 19,
        "h": 23
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "26": {
      "frame": {
        "x": 45,
        "y": 109,
        "w": 21,
        "h": 26
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 3,
        "y": 3,
        "w": 19,
        "h": 24
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "27": {
      "frame": {
        "x": 67,
        "y": 109,
        "w": 19,
        "h": 25
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 4,
        "y": 4,
        "w": 17,
        "h": 23
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "28": {
      "frame": {
        "x": 87,
        "y": 109,
        "w": 18,
        "h": 25
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 5,
        "y": 5,
        "w": 16,
        "h": 23
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "29": {
      "frame": {
        "x": 106,
        "y": 109,
        "w": 21,
        "h": 26
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 3,
        "y": 3,
        "w": 19,
        "h": 24
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "30": {
      "frame": {
        "x": 1,
        "y": 136,
        "w": 19,
        "h": 25
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 4,
        "y": 4,
        "w": 17,
        "h": 23
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "31": {
      "frame": {
        "x": 21,
        "y": 136,
        "w": 18,
        "h": 25
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 5,
        "y": 5,
        "w": 16,
        "h": 23
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "32": {
      "frame": {
        "x": 40,
        "y": 136,
        "w": 19,
        "h": 26
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 4,
        "y": 3,
        "w": 17,
        "h": 24
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "33": {
      "frame": {
        "x": 60,
        "y": 136,
        "w": 19,
        "h": 25
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 4,
        "y": 4,
        "w": 17,
        "h": 23
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "34": {
      "frame": {
        "x": 80,
        "y": 136,
        "w": 19,
        "h": 25
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 4,
        "y": 5,
        "w": 17,
        "h": 23
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "35": {
      "frame": {
        "x": 100,
        "y": 136,
        "w": 19,
        "h": 26
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 4,
        "y": 3,
        "w": 17,
        "h": 24
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "36": {
      "frame": {
        "x": 1,
        "y": 163,
        "w": 19,
        "h": 25
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 4,
        "y": 4,
        "w": 17,
        "h": 23
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "37": {
      "frame": {
        "x": 21,
        "y": 163,
        "w": 19,
        "h": 25
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 4,
        "y": 5,
        "w": 17,
        "h": 23
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "38": {
      "frame": {
        "x": 41,
        "y": 163,
        "w": 21,
        "h": 24
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 3,
        "y": 3,
        "w": 19,
        "h": 22
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "39": {
      "frame": {
        "x": 63,
        "y": 163,
        "w": 21,
        "h": 24
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 3,
        "y": 3,
        "w": 19,
        "h": 22
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "40": {
      "frame": {
        "x": 85,
        "y": 163,
        "w": 18,
        "h": 26
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 6,
        "y": 3,
        "w": 16,
        "h": 24
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "41": {
      "frame": {
        "x": 104,
        "y": 163,
        "w": 18,
        "h": 26
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 6,
        "y": 3,
        "w": 16,
        "h": 24
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "42": {
      "frame": {
        "x": 1,
        "y": 190,
        "w": 18,
        "h": 25
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 6,
        "y": 4,
        "w": 16,
        "h": 23
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "43": {
      "frame": {
        "x": 20,
        "y": 190,
        "w": 18,
        "h": 25
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 6,
        "y": 4,
        "w": 16,
        "h": 23
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "44": {
      "frame": {
        "x": 39,
        "y": 190,
        "w": 18,
        "h": 25
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 6,
        "y": 4,
        "w": 16,
        "h": 23
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "45": {
      "frame": {
        "x": 58,
        "y": 190,
        "w": 18,
        "h": 25
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 6,
        "y": 4,
        "w": 16,
        "h": 23
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "46": {
      "frame": {
        "x": 77,
        "y": 190,
        "w": 18,
        "h": 26
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 6,
        "y": 3,
        "w": 16,
        "h": 24
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "47": {
      "frame": {
        "x": 96,
        "y": 190,
        "w": 18,
        "h": 26
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 6,
        "y": 3,
        "w": 16,
        "h": 24
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "48": {
      "frame": {
        "x": 1,
        "y": 217,
        "w": 18,
        "h": 25
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 6,
        "y": 4,
        "w": 16,
        "h": 23
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "49": {
      "frame": {
        "x": 20,
        "y": 217,
        "w": 18,
        "h": 26
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 6,
        "y": 3,
        "w": 16,
        "h": 24
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "50": {
      "frame": {
        "x": 39,
        "y": 217,
        "w": 18,
        "h": 26
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 6,
        "y": 3,
        "w": 16,
        "h": 24
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "51": {
      "frame": {
        "x": 58,
        "y": 217,
        "w": 18,
        "h": 25
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 6,
        "y": 4,
        "w": 16,
        "h": 23
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "52": {
      "frame": {
        "x": 77,
        "y": 217,
        "w": 18,
        "h": 26
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 6,
        "y": 3,
        "w": 16,
        "h": 24
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "53": {
      "frame": {
        "x": 96,
        "y": 217,
        "w": 18,
        "h": 26
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 6,
        "y": 3,
        "w": 16,
        "h": 24
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "54": {
      "frame": {
        "x": 1,
        "y": 244,
        "w": 18,
        "h": 25
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 6,
        "y": 4,
        "w": 16,
        "h": 23
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "55": {
      "frame": {
        "x": 20,
        "y": 244,
        "w": 18,
        "h": 26
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 6,
        "y": 3,
        "w": 16,
        "h": 24
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "56": {
      "frame": {
        "x": 39,
        "y": 244,
        "w": 18,
        "h": 26
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 6,
        "y": 3,
        "w": 16,
        "h": 24
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "57": {
      "frame": {
        "x": 58,
        "y": 244,
        "w": 18,
        "h": 25
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 6,
        "y": 4,
        "w": 16,
        "h": 23
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "58": {
      "frame": {
        "x": 77,
        "y": 244,
        "w": 18,
        "h": 25
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 6,
        "y": 3,
        "w": 16,
        "h": 23
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "59": {
      "frame": {
        "x": 96,
        "y": 244,
        "w": 18,
        "h": 25
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 6,
        "y": 3,
        "w": 16,
        "h": 23
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "60": {
      "frame": {
        "x": 1,
        "y": 271,
        "w": 18,
        "h": 26
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 5,
        "y": 3,
        "w": 16,
        "h": 24
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "61": {
      "frame": {
        "x": 20,
        "y": 271,
        "w": 18,
        "h": 26
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 5,
        "y": 3,
        "w": 16,
        "h": 24
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "62": {
      "frame": {
        "x": 39,
        "y": 271,
        "w": 18,
        "h": 25
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 5,
        "y": 4,
        "w": 16,
        "h": 23
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "63": {
      "frame": {
        "x": 58,
        "y": 271,
        "w": 18,
        "h": 25
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 5,
        "y": 4,
        "w": 16,
        "h": 23
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "64": {
      "frame": {
        "x": 77,
        "y": 271,
        "w": 18,
        "h": 25
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 5,
        "y": 4,
        "w": 16,
        "h": 23
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "65": {
      "frame": {
        "x": 96,
        "y": 271,
        "w": 18,
        "h": 25
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 5,
        "y": 4,
        "w": 16,
        "h": 23
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "66": {
      "frame": {
        "x": 1,
        "y": 298,
        "w": 18,
        "h": 26
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 5,
        "y": 3,
        "w": 16,
        "h": 24
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "67": {
      "frame": {
        "x": 20,
        "y": 298,
        "w": 18,
        "h": 26
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 5,
        "y": 3,
        "w": 16,
        "h": 24
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "68": {
      "frame": {
        "x": 39,
        "y": 298,
        "w": 18,
        "h": 25
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 5,
        "y": 4,
        "w": 16,
        "h": 23
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "69": {
      "frame": {
        "x": 58,
        "y": 298,
        "w": 18,
        "h": 26
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 5,
        "y": 3,
        "w": 16,
        "h": 24
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "70": {
      "frame": {
        "x": 77,
        "y": 298,
        "w": 18,
        "h": 26
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 5,
        "y": 3,
        "w": 16,
        "h": 24
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "71": {
      "frame": {
        "x": 96,
        "y": 298,
        "w": 18,
        "h": 25
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 5,
        "y": 4,
        "w": 16,
        "h": 23
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "72": {
      "frame": {
        "x": 1,
        "y": 325,
        "w": 18,
        "h": 26
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 5,
        "y": 3,
        "w": 16,
        "h": 24
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "73": {
      "frame": {
        "x": 20,
        "y": 325,
        "w": 18,
        "h": 26
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 5,
        "y": 3,
        "w": 16,
        "h": 24
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "74": {
      "frame": {
        "x": 39,
        "y": 325,
        "w": 18,
        "h": 25
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 5,
        "y": 4,
        "w": 16,
        "h": 23
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "75": {
      "frame": {
        "x": 58,
        "y": 325,
        "w": 18,
        "h": 26
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 5,
        "y": 3,
        "w": 16,
        "h": 24
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "76": {
      "frame": {
        "x": 77,
        "y": 325,
        "w": 18,
        "h": 26
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 5,
        "y": 3,
        "w": 16,
        "h": 24
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "77": {
      "frame": {
        "x": 96,
        "y": 325,
        "w": 18,
        "h": 25
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 5,
        "y": 4,
        "w": 16,
        "h": 23
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "78": {
      "frame": {
        "x": 1,
        "y": 352,
        "w": 18,
        "h": 25
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 5,
        "y": 3,
        "w": 16,
        "h": 23
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    },
    "79": {
      "frame": {
        "x": 20,
        "y": 352,
        "w": 18,
        "h": 25
      },
      "rotated": false,
      "trimmed": true,
      "spriteSourceSize": {
        "x": 5,
        "y": 3,
        "w": 16,
        "h": 23
      },
      "sourceSize": {
        "w": 25,
        "h": 28
      },
      "duration": 140
    }
  },
  "meta": {
    "app": "https://www.aseprite.org/",
    "version": "1.2.34.1-x64",
    "image": "player.png",
    "format": "RGBA8888",
    "size": {
      "w": 132,
      "h": 377
    },
    "scale": "1",
    "frameTags": [
      {
        "name": "PLAYER_IDLE_D",
        "from": 0,
        "to": 5,
        "direction": "forward"
      },
      {
        "name": "PLAYER_WALK_D",
        "from": 6,
        "to": 11,
        "direction": "forward"
      },
      {
        "name": "PLAYER_PUSH_D",
        "from": 12,
        "to": 17,
        "direction": "forward"
      },
      {
        "name": "PLAYER_JUMP_D",
        "from": 18,
        "to": 19,
        "direction": "forward"
      },
      {
        "name": "PLAYER_IDLE_U",
        "from": 20,
        "to": 25,
        "direction": "forward"
      },
      {
        "name": "PLAYER_WALK_U",
        "from": 26,
        "to": 31,
        "direction": "forward"
      },
      {
        "name": "PLAYER_PUSH_U",
        "from": 32,
        "to": 37,
        "direction": "forward"
      },
      {
        "name": "PLAYER_JUMP_U",
        "from": 38,
        "to": 39,
        "direction": "forward"
      },
      {
        "name": "PLAYER_IDLE_R",
        "from": 40,
        "to": 45,
        "direction": "forward"
      },
      {
        "name": "PLAYER_WALK_R",
        "from": 46,
        "to": 51,
        "direction": "forward"
      },
      {
        "name": "PLAYER_PUSH_R",
        "from": 52,
        "to": 57,
        "direction": "forward"
      },
      {
        "name": "PLAYER_JUMP_R",
        "from": 58,
        "to": 59,
        "direction": "forward"
      },
      {
        "name": "PLAYER_IDLE_L",
        "from": 60,
        "to": 65,
        "direction": "forward"
      },
      {
        "name": "PLAYER_WALK_L",
        "from": 66,
        "to": 71,
        "direction": "forward"
      },
      {
        "name": "PLAYER_PUSH_L",
        "from": 72,
        "to": 77,
        "direction": "forward"
      },
      {
        "name": "PLAYER_JUMP_L",
        "from": 78,
        "to": 79,
        "direction": "forward"
      }
    ]
  }
}
```

**Comment by samme** [comment]
Can you show the difference between v3.55.2 and 3.60.0-beta.17?

**Comment by likwidgames** [comment]
@samme  

Here you go:
https://codesandbox.io/s/distorted-sprites-3-55-v3snc8?file=/package.json

**Comment by samme** [comment]
They look identical to me. 

![distorted sprites 3600b17](https://user-images.githubusercontent.com/435681/219822353-a598cfaf-544a-4e9a-b029-359b14bcb9b8.png)
![distorted sprites 3552](https://user-images.githubusercontent.com/435681/219822355-fcfba1ad-7339-45f3-84b0-96f688e84834.png)

**Comment by likwidgames** [comment]
> They look identical to me.
> 
> ![distorted sprites 3600b17](https://user-images.githubusercontent.com/435681/219822353-a598cfaf-544a-4e9a-b029-359b14bcb9b8.png) ![distorted sprites 3552](https://user-images.githubusercontent.com/435681/219822355-fcfba1ad-7339-45f3-84b0-96f688e84834.png)

Definitely not the case for me. It happens when you run the code and watch the animated character on the top left. The link on the OP has a large amount of distortion on the character. I can take a video if you need.

**Comment by photonstorm** [comment]
It works fine until 3.60 Beta 11. All Beta versions prior 11 render correctly. So something between 10 and 11 caused this.

**Comment by photonstorm** [comment]
As suspected, this was nothing to do with Aseprite, but rather the use of 'zoom' and 'pixelArt' in the game config, along with the way in which pixel rounding is calculated in Beta 11. Pretty sure this is fixed now, although it doesn't happen at all on my main work PC as I don't have a HighDPI display (and it only manifests on those, even in your original example). Will re-test on my iMac at home, but the current commit should be good.

**Comment by likwidgames** [comment]
> As suspected, this was nothing to do with Aseprite, but rather the use of 'zoom' and 'pixelArt' in the game config, along with the way in which pixel rounding is calculated in Beta 11. Pretty sure this is fixed now, although it doesn't happen at all on my main work PC as I don't have a HighDPI display (and it only manifests on those, even in your original example). Will re-test on my iMac at home, but the current commit should be good.

I created a fork that uses 3.60.0-beta.20 and the issue remains:
https://codesandbox.io/s/distorted-sprites-forked-ndeinm?file=/package.json

**Comment by photonstorm** [comment]
It's Beta 22 that has the fix for this in.

**Comment by likwidgames** [comment]
> It's Beta 22 that has the fix for this in.

Can confirm this is fixed in Beta 22. Thank you!
