### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'duration')

### ISSUE THREAD

**Issue by 95y** [phaserjs/phaser#6409]
import kingSpritesheet from '../assets/king.png'
import kingSpritesheetJSON from '../assets/king.json'

preload() {
 this.load.aseprite('king-spritesheet', kingSpritesheet, kingSpritesheetJSON)
}

create() {
 this.anims.createFromAseprite('king-spritesheet')
 this.king = this.add.sprite(400, 300, 'king-spritesheet')
      this.king.anims.play({
        key: 'Idle',
        repeat: -1
      })
}

Question: Is my json file faulty or am I using it incorrectly?

The king.json content is:

[归档.zip](https://github.com/photonstorm/phaser/files/10871226/default.zip)

**Comment by photonstorm** [comment]
This sounds like #6410 which is already fixed. Please test this against 3.60 Beta 19 and report back.

**Comment by 95y** [comment]
> 这听起来像#6410已经修复了。请针对 3.60 Beta 19 对此进行测试并报告。

"phaser": "^3.60.0-beta.19"

<img width="783" alt="image" src="https://user-images.githubusercontent.com/22910181/222615517-2d88781a-c727-4b25-a63c-dc08d3953f56.png">


The test file is at the top.

**Comment by 95y** [comment]
> 这听起来像#6410已经修复了。请针对 3.60 Beta 19 对此进行测试并报告。

I have switched to v3.60 Beta.19 but I still have the same problem.
<img width="417" alt="image" src="https://user-images.githubusercontent.com/22910181/222615763-aec40153-7967-4744-8f80-d50cadd2f6d5.png">

<img width="788" alt="image" src="https://user-images.githubusercontent.com/22910181/222615776-273edb86-abf2-4799-a8ba-9c81d20896b4.png">


The test file is at the top.

**Comment by 95y** [comment]
<img width="790" alt="image" src="https://user-images.githubusercontent.com/22910181/222615924-75f34956-5cae-477f-b14d-446d9ab47bf6.png">

**Comment by 95y** [comment]
json file problem..
