### ISSUE TITLE
Post FX Bloom does not take into account canvas Resize

### ISSUE THREAD

**Issue by Nerodon** [phaserjs/phaser#6677]
## Version

* Phaser Version: 3.70.0

* Operating system: Windows 11

* Browser: FF and Chrome

## Description

Hello, really liking the new bloom post effect, but it seems to have an issue with canvas resizing. I'm not aware of any workarounds at the moment.

## Example Test Code

Example [here](https://jsfiddle.net/tge7rx0y/17/)
Use the mouse wheel to resize and see the bloom effect moving away from the image

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by seansps** [comment]
https://github.com/phaserjs/phaser/issues/6503#issuecomment-2049994114
Maybe I should have posted this here, but in the latest version, I am still seeing problems on resize when using Blur
