### ISSUE TITLE
Layer destroy throwing error on scene end

### ISSUE THREAD

**Issue by Petah** [phaserjs/phaser#6724]
## Version

* Phaser Version: 3.70

* Operating system: OSX

* Browser: Chrome

## Description

When using layers and a scene ends it throws an error `Uncaught TypeError: Cannot read properties of undefined (reading 'destroy')`

## Example Test Code

 Based on this example, just adding a stop after 1 second causes the error: https://labs.phaser.io/edit.html?src=src/game%20objects/layer/add%20sprite%20to%20layer.js&v=3.70.0

```
class Example extends Phaser.Scene
{
    preload ()
    {
        this.load.image('spaceman', 'assets/sprites/exocet_spaceman.png');
    }

    create ()
    {
        const spaceman = this.add.sprite(150, 300, 'spaceman');
        const layer = this.add.layer();
        layer.add([ spaceman ]);
        setTimeout(() => {
            this.scene.stop()
        }, 1000)
    }
}

const config = {
    type: Phaser.AUTO,
    width: 800,
    height: 600,
    backgroundColor: '#2d2d2d',
    parent: 'phaser-example',
    scene: Example
};

const game = new Phaser.Game(config);
```

## Additional Information

<img width="1676" alt="image" src="https://github.com/phaserjs/phaser/assets/117625844/1df27b78-c499-4ed3-924a-a47af4824993">

**Comment by photonstorm** [comment]
Thank you for spending time reporting this issue. We've already fixed this in the `master` branch of Phaser and it will be part of the next official release. You can track what's already been fixed by searching closed issues, or by looking at the [Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md).

**Comment by Petah** [comment]
@photonstorm I tested it out by using `"phaser": "git+https://github.com/phaserjs/phaser.git#master"` in my project, but still get the error. I also don't see it mentioned here: https://github.com/phaserjs/phaser/blob/master/changelog/3.80/CHANGELOG-v3.80.md

Is there a way to test with the https://labs.phaser.io/ website using the master branch?

**Comment by Petah** [comment]
Oh it looks like there is some open PRs about it, but not yet merged.

**Comment by photonstorm** [comment]
Closing as a duplicate of #6675 - looking into it now. Please track on that issue.
