### ISSUE TITLE
Nineslice objects flickering

### ISSUE THREAD

**Issue by Allabreve** [phaserjs/phaser#6922]
## Version

* Phaser Version: 3.86.0

* Operating system: Win11

* Browser: Chrome, Firefox, Edge

## Description

When creating, animating and destroying a lot of nine-slice objects the remaining alive nine-slices will eventually start flickering.

Expected behavior: All nine-slices finish their animation without glitches.

## Example Test Code

https://phaser.io/sandbox/GQSpWrP5

## Additional Information

To reproduce the issue open the example sandbox and let it run until objects start leaving the screen.

If the number of objects is reduced (By increasing the "interval" or decreasing the "duration") the flickering stops.

Additionally the flickering can reproduced if using mor complex objects alongside the nine-slices.
(Original Scenario: A particle system with container. Containing images texts and nine-slices as background.

**Comment by Allabreve** [comment]
One addition: it seems the issue is resolved in TP5.

Is there any eta on this issue before 3.90 or does it have any priority at all?

I got a kickoff in a month and would like to know if I should roll out my own Nineslice.

**Comment by BenjaminDRichards** [comment]
Hi - thanks for bringing this to our attention, and apologies for not addressing it sooner.

TP5 was ancestral to what is now Phaser v4, now very close to release. The issue remains resolved, per my stress-testing.

I'm not sure what the problem was exactly. I suspect an error with batch size handling, as a NineSlice is composed of several quads drawn together. This process was rewritten for Phaser v4, and should avoid trying to add too much to a batch. Batches are also the maximum possible size in Phaser v4 (16K quads), so a test scene that requires 10 draw calls in v3 takes just 3 in v4.
